# Summary: Numpy

In [66]:
import numpy as np

## 1. array 만들기
- arrange()
- array([])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

## 2. 크기 (size, shape, dim)

- np.size
- np.shape
- np.dim

In [60]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a.shape #모양

(2, 5)

In [12]:
a.ndim #차원

2

In [51]:
a.size #원소의 개수

3

## 3. type

- a.dtype
- type(a)

In [61]:
a.dtype #numpy의 element의 data type은 항상 동일해야 함!!

dtype('int64')

In [15]:
type(a)

numpy.ndarray

## 4. 빈번한 에러

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.array([1,1,1], dtype=float)
a

array([1., 1., 1.])

## 5. 특수 행렬 : 0행렬, 1행렬, 단위 행렬, zeros, ones, eye

- np.zeros([])
- np.ones([])
- np.eye()

In [20]:
z = np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
o = np.ones([3,3])
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 6. random

- np.random.randint
- np.random.choice
- np.random.permutation

In [23]:
r = np.random.randint(1,10)
r

9

In [24]:
np.random.randint(low=1, high=10, size=8).reshape(2,4)

array([[6, 3, 7, 8],
       [4, 8, 3, 7]])

In [25]:
np.random.choice(11, 10, replace=False)

array([ 2,  7,  6,  4,  1,  5, 10,  9,  3,  0])

In [34]:
numbers = np.random.choice(46, 6, replace=False) # 0 ~ 45까지 6개 정수 숫지
numbers 

array([45,  0, 40, 28, 42, 33])

In [44]:
from numpy.random import permutation
np.sort((permutation(46))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [50]:
np.sort((permutation(46))).reshape(2,23)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45]])

In [47]:
np.sort((permutation(46)[:6]))

array([ 6, 19, 32, 41, 44, 45])

## 7. reshape, flatten

- np.reshape()
- np.flatten()

In [55]:
x = np.array([[2,3,4],[4,5,6],[3,2,0]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [3, 2, 0]])

In [57]:
x.reshape(1,9)

array([[2, 3, 4, 4, 5, 6, 3, 2, 0]])

In [64]:
x = np.array([(1, 2),(2, 3)])

In [65]:
x.flatten()

array([1, 2, 2, 3])